apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eugl19uaz-python
  janus-idp.io/tekton: eugl19uaz-python
  backstage.io/kubernetes-id: eugl19uaz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eugl19uaz-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
